spring:
  profiles:
    active:
      -dev

---
server:
  port: 8001


spring:
  profiles: dev
  application:
    name: microservicecloud-config-dept-1                                            #对外暴露的微服务名字,注册到eureka时就是这个名字的大写
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://10.141.211.169:3306/cloudDB01?characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                                              #数据库连接池的最小维持连接数
      initial-size: 5                                                          #初始化连接数
      max-total: 5                                                             #最大连接数
      max-wait-millis: 200                                                     #等待连接获取的最大超时时间

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: cn.edu.fudan.springcloud.entities
  mapper-locations: classpath:mybatis/mapper/**/*.xml

eureka:
  client:                                                                     #将当前服务注册进eureka服务列表
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka                               #eureka所在的URL,和eureka server中配置的要一致
  instance:
    instance-id: microservicecloud-dept8001                                   #eureka的status栏所显示的内容
    prefer-ip-address: true                                                   #eureka的status栏每一项鼠标放上去链接会显示IP

info:
  app.name: fudan-microservicecloud
  company.name: www.fudan.edu.cn
  build.artifactId: $project.artifactId$
  build.version: $project.version$
---
#其它环境的配置